version: 2
updates:
  - package-ecosystem: npm
    directory: /v3/frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      frontend-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /v3/e2e
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      e2e-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
