function q(code, level, prompt, passage, options, correct) {
  return { code, skill: 'LISTENING', level, prompt, passage, options: options.map((label, index) => ({ id: String.fromCharCode(97 + index), label })), correct, explanation: 'Listening diagnostic item.' }
}
module.exports = [
  q('li-c1-01','C1',"Which idea best summarises the speaker's argument?","We tend to imagine creativity requires complete freedom, yet constraints can force us to question habits we'd otherwise leave untouched. A limited budget may even produce a simpler and ultimately better solution.",['Constraints can stimulate inventive solutions','Creative work needs unlimited budgets','Deadlines always reduce quality','Innovation is mostly individual'],'a'),
  q('li-c1-02','C1',"What is the speaker's attitude to the findings?",'The early results are encouraging, especially because three independent teams have observed similar effects. Even so, the samples remain small and the follow-up periods short, so I would hesitate to call the intervention proven.',['Entirely dismissive','Cautiously positive','Completely convinced','Uninterested'],'b'),
  q('li-c1-03','C1','Why does the speaker mention historical records?',"Recent images show the shoreline retreating quickly, and some blame the latest construction project entirely. Historical records, however, show that the coast had been shifting for decades. The project may have accelerated the trend, but it didn't start it.",['To prove modern images are wrong','To defend the construction project completely','To challenge an overly simple explanation','To show the coast never changes'],'c'),
  q('li-c1-04','C1','What does the speaker imply about expertise?','Public debate often rewards certainty, but genuine expertise includes knowing where the evidence becomes weak. A specialist who distinguishes strong conclusions from plausible speculation may sound less decisive, yet may be more accurate.',['Experts should never express doubt','Confidence proves expertise','Specialists usually agree','Recognising uncertainty can be a sign of expertise'],'d'),
  q('li-c2-01','C2','What subtle criticism is the speaker making?','The authority describes its consultation as evidence of openness. Curiously, the construction timetable was approved before residents were invited to comment, leaving one to wonder which parts of the proposal remain genuinely negotiable.',['The consultation may be more symbolic than influential','Residents refuse to participate','The project has been cancelled','The timetable is too long'],'a'),
  q('li-c2-02','C2','What paradox does the speaker identify?','As datasets grow, some estimates become more precise. Yet the same wealth of information reveals interactions that smaller studies could not detect. We know more, but we also become more aware of what we still do not understand.',['Large datasets make research impossible','More knowledge can make uncertainty more visible','Precision always removes uncertainty','Small studies are always superior'],'b'),
  q('li-c2-03','C2',"How does the speaker characterise the company's new wording?",'The company no longer calls the programme a reduction in services; it now speaks of a rebalancing of provision. The activities being removed are much the same. What has changed most noticeably is the vocabulary used to announce their disappearance.',['As a technical correction','As an admission of failure','As language that softens an uncomfortable reality','As a legal requirement'],'c'),
  q('li-c2-04','C2','What does the speaker imply about the unanimous vote?','The committee eventually endorsed the proposal unanimously, but unanimity of voting should not be confused with unanimity of reasoning. Some saw it as the ideal solution; others supported it only because every alternative appeared worse.',['Everyone used the same reasoning','The evidence was conclusive','No member had reservations','Agreement on the decision concealed different motivations'],'d'),
]
