function q(code, level, prompt, passage, options, correct) {
  return { code, skill: 'LISTENING', level, prompt, passage, options: options.map((label, index) => ({ id: String.fromCharCode(97 + index), label })), correct, explanation: 'Listening diagnostic item.' }
}
module.exports = [
  q('li-b1-01','B1','What is the main reason Daniel prefers the earlier train?','The later train is usually quieter, but I take the 7:15 because it gets me to the office before the traffic around the station becomes difficult.',['It helps him avoid busy traffic','It is cheaper','It has better seats','It is quieter'],'a'),
  q('li-b1-02','B1','What does the speaker think about the course?',"At first I thought the course would be too technical for me. The first session was challenging, but the practical examples made everything much clearer, and now I'm glad I enrolled.",['It was a waste of time','It became useful after a difficult start','It was too easy','It should be shorter'],'b'),
  q('li-b1-03','B1','Why will the shop close early?',"Just a reminder that we'll close at four instead of six this Friday because the staff are attending a training session.",['There is a public holiday','The building needs repairs','Staff have training','There are no customers'],'c'),
  q('li-b1-04','B1','What advice does the speaker give?',"If you want to improve your pronunciation, don't try to practise for two hours once a week. Ten focused minutes every day will probably help you more.",['Study only at weekends','Avoid speaking aloud','Practise for two hours','Practise briefly but regularly'],'d'),
  q('li-b2-01','B2',"What is the speaker's main point about remote work?",'People often ask whether remote work is productive or unproductive, as if there were one answer. In my experience, the result depends far more on communication, expectations and the kind of work a team actually does.',['Its success depends on how work is organised','It is always more productive','It should replace offices','It only suits managers'],'a'),
  q('li-b2-02','B2','Why was the first plan criticised?','The original transport plan assumed most residents drove straight into the centre. Later surveys showed that many combine buses, walking and short car journeys, so critics said the plan was solving the wrong problem.',['It was too expensive','It was based on an inaccurate travel pattern','It removed all buses','It focused on visitors'],'b'),
  q('li-b2-03','B2','What does the speaker imply about the restaurant?','When we opened, people loved the location but found the menu confusing. We simplified it and introduced seasonal dishes. Since then, the number of returning customers has risen steadily.',['The location changed','Prices were reduced','Customer feedback helped improve the business','The restaurant became smaller'],'c'),
  q('li-b2-04','B2','What concern is raised about performance targets?','A target can be useful until people are rewarded only for hitting that number. Then they may optimise the metric itself rather than the wider outcome the metric was meant to represent.',['Targets are impossible to measure','Managers dislike data','Teams need more targets','A metric can distort the behaviour it measures'],'d'),
]
