import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router'
import App from './app/App'
import AppErrorBoundary from './components/AppErrorBoundary'
import ScrollToTop from './components/ScrollToTop'
import StudentCampusEntryProgress from './components/StudentCampusEntryProgress'
import { AuthProvider } from './features/auth/AuthProvider'
import './styles/global.css'
import './styles/public-pages.css'
import './styles/admin-cms.css'
import './styles/admin-students.css'
import './styles/admin-academy.css'
import './styles/admin-settings.css'
import './styles/admin-contacts.css'
import './styles/admin-notifications.css'
import './styles/admin-system.css'
import './styles/account-profile.css'
import './styles/auth-session.css'
import './styles/student-portal.css'
import './styles/teacher-portal.css'
import './styles/accessibility.css'
import './styles/error-states.css'
import './styles/dashboard-navigation.css'
import './styles/pilot-readiness.css'
import './styles/visual-refresh.css'
import './styles/home-premium-v2.css'
import './styles/home-premium-v2-shell.css'
import './styles/home-premium-v2-phase2.css'
import './styles/home-premium-v2-phase2-fix.css'
import './styles/home-premium-v2-phase3.css'
import './styles/home-premium-v2-phase7c1.css'
import './styles/home-premium-v2-phase7c2.css'
import './styles/home-premium-v2-phase7c3.css'
import './styles/home-premium-v2-phase7c4.css'
import './styles/home-premium-v2-phase7c5.css'
import './styles/home-premium-v2-phase7c6.css'
import './styles/programs-premium-v2.css'
import './styles/programs-premium-v2-phase7d.css'
import './styles/course-detail-premium-v2.css'
import './styles/teachers-premium-v2.css'
import './styles/teachers-premium-v2-phase2.css'
import './styles/teachers-premium-v2-phase7e.css'
import './styles/teachers-premium-v2-phase7e2.css'
import './styles/about-premium-v2.css'
import './styles/about-premium-v2-phase2.css'
import './styles/about-premium-v2-phase7e.css'
import './styles/pricing-premium-v2.css'
import './styles/pricing-premium-v2-phase2.css'
import './styles/contact-premium-v2.css'
import './styles/contact-security-phase9.css'
import './styles/conversion-pages-phase7f.css'
import './styles/conversion-pages-phase7f2.css'
import './styles/blog-premium-v2.css'
import './styles/blog-premium-v2-phase7g.css'
import './styles/access-premium-v2.css'
import './styles/premium-visual-assets.css'
import './styles/portal-role-premium-v2.css'
import './styles/student-dashboard-premium-v2.css'
import './styles/photography-pass-v2.css'
import './styles/premium-completion-pass.css'
import './styles/premium-detail-pass-v2.css'
import './styles/admin-visual-map-v2.css'
import './styles/cms-functional-closeout.css'
import './styles/public-premium-v2-shell.css'
import './styles/public-shell-viewport-guard.css'
import './styles/public-heroes-phase7j1.css'
import './styles/programs-phase7j2.css'
import './styles/public-consent-whatsapp.css'
import './styles/admin-privacy-settings.css'
import './styles/white-canvas-phase7j6.css'
import './styles/home-structure-phase7j7.css'
import './styles/student-campus-phase8a1.css'
import './styles/class-delivery-phase8a2.css'
import './styles/student-campus-phase10a.css'
import './styles/student-online-class-phase9.css'
import './styles/student-campus-phase10b.css'
import './styles/student-campus-phase10c.css'
import './styles/student-campus-phase10d.css'
import './styles/zoom-integration-phase8b1.css'
import './styles/placement-test-phase8c2.css'
import './styles/placement-conversion-phase8c3.css'
import './styles/student-level-phase8c4.css'
import './styles/student-campus-phase10e.css'
import './styles/student-campus-phase10f.css'
import './styles/student-campus-phase10g.css'
import './styles/student-campus-visual-polish.css'
import './styles/student-campus-phase10v1.css'
import './styles/student-campus-phase10v2.css'
import './styles/student-campus-phase10v3.css'
import './styles/student-campus-phase10v4.css'
import './styles/student-campus-phase10v5.css'
import './styles/student-campus-phase10v6.css'
import './styles/student-campus-phase10v7-v9.css'
import './styles/teacher-campus-phase11a.css'
import './styles/teacher-campus-phase11b.css'
import './styles/teacher-levels-phase8c5.css'
import './styles/teacher-campus-phase11c.css'
import './styles/teacher-campus-phase11d.css'
import './styles/teacher-campus-phase11e.css'
import './styles/teacher-campus-phase11f.css'
import './styles/teacher-campus-phase11g.css'
import './styles/teacher-campus-phase11h.css'
import './styles/teacher-campus-phase11i.css'
import './styles/teacher-campus-phase11j.css'
import './styles/calendar-phase13a.css'
import './styles/admin-payments-phase13.css'
import './styles/admin-campus-phase12a.css'
import './styles/admin-campus-phase12b.css'
import './styles/admin-campus-phase12d.css'
import './styles/admin-campus-phase12d-responsive.css'
import './styles/admin-campus-phase12e.css'
import './styles/admin-campus-phase12e-metrics.css'
import './styles/admin-campus-phase12e-responsive.css'
import './styles/placement-admin-phase8c6.css'
import './styles/placement-results-phase8c6.css'
import './styles/placement-listening-phase8c8.css'
import './styles/admin-campus-phase12f.css'
import './styles/admin-campus-phase12g.css'
import './styles/admin-campus-phase12h.css'
import './styles/admin-campus-phase12i.css'
import './styles/visual-clarity-phase14a.css'
import './styles/teacher-clarity-phase14b.css'
import './styles/admin-profiles-phase14c.css'
import './styles/admin-courses-phase14d.css'
import './styles/admin-classes-phase14e.css'

const root = document.getElementById('root')
if (!root) throw new Error('No se ha encontrado el elemento #root')

createRoot(root).render(
  <StrictMode>
    <AppErrorBoundary>
      <BrowserRouter>
        <ScrollToTop />
        <StudentCampusEntryProgress />
        <AuthProvider><App /></AuthProvider>
      </BrowserRouter>
    </AppErrorBoundary>
  </StrictMode>,
)
