import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router'
import App from './app/App'
import AppErrorBoundary from './components/AppErrorBoundary'
import ScrollToTop from './components/ScrollToTop'
import { AuthProvider } from './features/auth/AuthProvider'
import './styles/global.css'
import './styles/public-pages.css'
import './styles/admin-cms.css'
import './styles/admin-students.css'
import './styles/admin-academy.css'
import './styles/admin-settings.css'
import './styles/admin-contacts.css'
import './styles/admin-notifications.css'
import './styles/admin-system.css'
import './styles/account-profile.css'
import './styles/auth-session.css'
import './styles/student-portal.css'
import './styles/teacher-portal.css'
import './styles/accessibility.css'
import './styles/error-states.css'
import './styles/dashboard-navigation.css'
import './styles/pilot-readiness.css'
import './styles/visual-refresh.css'
import './styles/home-premium-v2.css'
import './styles/home-premium-v2-shell.css'
import './styles/home-premium-v2-phase2.css'
import './styles/home-premium-v2-phase2-fix.css'
import './styles/home-premium-v2-phase3.css'
import './styles/home-premium-v2-phase7c1.css'
import './styles/home-premium-v2-phase7c2.css'
import './styles/home-premium-v2-phase7c3.css'
import './styles/home-premium-v2-phase7c4.css'
import './styles/home-premium-v2-phase7c5.css'
import './styles/home-premium-v2-phase7c6.css'
import './styles/programs-premium-v2.css'
import './styles/programs-premium-v2-phase7d.css'
import './styles/course-detail-premium-v2.css'
import './styles/teachers-premium-v2.css'
import './styles/teachers-premium-v2-phase2.css'
import './styles/teachers-premium-v2-phase7e.css'
import './styles/teachers-premium-v2-phase7e2.css'
import './styles/about-premium-v2.css'
import './styles/about-premium-v2-phase2.css'
import './styles/about-premium-v2-phase7e.css'
import './styles/pricing-premium-v2.css'
import './styles/pricing-premium-v2-phase2.css'
import './styles/contact-premium-v2.css'
import './styles/conversion-pages-phase7f.css'
import './styles/conversion-pages-phase7f2.css'
import './styles/blog-premium-v2.css'
import './styles/blog-premium-v2-phase7g.css'
import './styles/access-premium-v2.css'
import './styles/premium-visual-assets.css'
import './styles/portal-role-premium-v2.css'
import './styles/student-dashboard-premium-v2.css'
import './styles/photography-pass-v2.css'
import './styles/premium-completion-pass.css'
import './styles/premium-detail-pass-v2.css'
import './styles/admin-visual-map-v2.css'
import './styles/cms-functional-closeout.css'
import './styles/public-premium-v2-shell.css'
import './styles/public-shell-viewport-guard.css'
import './styles/public-heroes-phase7j1.css'
import './styles/programs-phase7j2.css'
import './styles/public-consent-whatsapp.css'
import './styles/admin-privacy-settings.css'
import './styles/white-canvas-phase7j6.css'
import './styles/home-structure-phase7j7.css'
import './styles/student-campus-phase8a1.css'
import './styles/class-delivery-phase8a2.css'
import './styles/zoom-integration-phase8b1.css'
import './styles/placement-test-phase8c2.css'
import './styles/placement-conversion-phase8c3.css'
import './styles/student-level-phase8c4.css'
import './styles/teacher-levels-phase8c5.css'
import './styles/placement-admin-phase8c6.css'
import './styles/placement-results-phase8c6.css'

const root = document.getElementById('root')
if (!root) throw new Error('No se ha encontrado el elemento #root')

createRoot(root).render(
  <StrictMode>
    <AppErrorBoundary>
      <BrowserRouter>
        <ScrollToTop />
        <AuthProvider><App /></AuthProvider>
      </BrowserRouter>
    </AppErrorBoundary>
  </StrictMode>,
)
